const COUNT_OF_ROW = 8
const COUNT_OF_COLUMN = 8
const COUNT_OF_TYPES = 5
const COUNT_OF_MIN_BLOCKS = 3
const STEP_OF_COLUMN = 1
const TIME_OF_ANIMATION = 300

const DIRECTION = {
  UPPER: -COUNT_OF_COLUMN,
  UNDER: COUNT_OF_COLUMN,
  LEFT: -STEP_OF_COLUMN,
  RIGHT: STEP_OF_COLUMN,
  LEFT_UPPER: -COUNT_OF_COLUMN - STEP_OF_COLUMN,
  RIGHT_UPPER: -COUNT_OF_COLUMN + STEP_OF_COLUMN,
  LEFT_UNDER: COUNT_OF_COLUMN - STEP_OF_COLUMN,
  RIGHT_UNDER: COUNT_OF_COLUMN + STEP_OF_COLUMN
}